name: Build Deploy Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-deploy-release:
    name: Build Deploy Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Node packages
      uses: bahmutov/npm-install@v1

    - name: Build dist files
      run: yarn build

    - name: Build readme.txt
      run: yarn auto-changelog -p --output readme.txt --template readme.hbs --commit-limit false

    - name: Deploy to WordPress SVN
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      with:
        generate-zip: true

    - name: Save previous Git tag
      id: save_previous
      run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)

    - name: Save current Git tag
      id: save_current
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Build temporary changelog
      run: git log --pretty=format:"* %s (%h)" ${{steps.save_previous.outputs.tag}}..${{steps.save_current.outputs.tag}} > temp-changelog.txt

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        body_path: temp-changelog.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
