name: Demo

on:
  push:
    branches:
      - master

jobs:
  update-demo:
    name: Update Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node packages
        uses: bahmutov/npm-install@v1
      - name: Build demo files
        run: yarn build:demo
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: demo
