name: Demo

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node packages
        uses: bahmutov/npm-install@v1
      - name: Build demo files
        run: yarn build-demo
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: demo
