name: Lint Deploy Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node packages
      uses: bahmutov/npm-install@v1
    - name: Run Prettier
      run: yarn prettier --check '**/*.{js,php,md}'
    - name: Run ESLint
      run: yarn eslint '**/*.js'

  deploy:
    needs: lint
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Node packages
      uses: bahmutov/npm-install@v1
    - name: Build dist files
      run: yarn build
    - name: Build readme.txt
      run: yarn auto-changelog -p --output readme.txt --template readme.hbs --commit-limit false --ignore-commit-pattern "Release ?\d+\.\d+\.\d+"
    - name: Deploy to WordPress SVN
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      with:
        generate-zip: true
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: ${{github.workspace}}/${{ github.event.repository.name }}.zip

  release:
    needs: deploy
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Save previous Git tag
      id: save_previous
      run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
    - name: Build temporary changelog
      run: git log --pretty=format:"* %s (%h)" ${{steps.save_previous.outputs.tag}}..HEAD^1 > temp-changelog.txt
    - name: Download release artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.event.repository.name }}.zip
        body_path: temp-changelog.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
