name: PR Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node packages
      uses: bahmutov/npm-install@v1
    - name: Run Prettier
      run: yarn prettier --check '**/*.{js,php,md}'
    - name: Run ESLint
      run: yarn eslint '**/*.js'
