name: Weekly "Tested up to" check

on:
    schedule:
        - cron: '0 0 * * 0' # Every Sunday at midnight
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    tut-check:
        name: Check for new "Tested up to" version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run wp-tut-updater-action
              uses: AlecRust/wp-tut-updater-action@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file-paths: .cliff/cliff-readme-txt.toml
